apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: php-pod
      labels:
        type: app
    spec:
      containers:
      - name: php-app
        image: 735729633608.dkr.ecr.us-east-1.amazonaws.com/php-new:latest
        ports:
        - containerPort: 80
          hostPort: 80
